### ISSUE TITLE
Crash closing the Options Menu

### ISSUE THREAD

**Issue by SAJewers** [rosebudmods/shut-up-realms#2] opened 2024-08-28 01:35 UTC
[crash-2024-08-27_22.31.52-client.txt](https://github.com/user-attachments/files/16773658/crash-2024-08-27_22.31.52-client.txt)

Disabling this mod fixed it. Not sure if it's a bug in the mod itself or an incompatibility with some other mod.

**Comment by eristhea** [comment] 2024-08-28 02:15
duplicate of #1, i'll be releasing 1.0.2 in a few minutes which fixes this issue!

**Comment by eristhea** [comment] 2024-08-28 02:15
(thank you anyway for reporting!)

**Closed as completed by eristhea** 2024-08-28 02:15 UTC
Labels: bug, duplicate
